[package]
name = "url-shortner"
version = "0.1.0"
edition = "2024"

[dependencies]
nanoid = "0.4.0"
once_cell = "1.21.3"
serde = { version = "1.0.228", features = ["derive"] }
tokio = "1.48.0"
uncovr = { version = "0.2.0", path = "../.." }
