[package]
name = "hello-api"
version = "0.1.0"
edition = "2021"

[dependencies]
uncover = { path = "../.." }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35", features = ["full"] }
schemars = { version = "0.8.16", features = ["derive"] }
