[package]
name = "routes"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
uncovr = { version = "0.2.0", path = "../.." }
